let
    Source = Excel.Workbook(File.Contents("C:\Users\RS singh\Desktop\Finance DATA analytics\Credit card Default Risk Analysis DATA.xlsx"), null, true),
    UCI_Credit_Card_Sheet = Source{[Item="UCI_Credit_Card",Kind="Sheet"]}[Data],
    #"Promoted Headers" = Table.PromoteHeaders(UCI_Credit_Card_Sheet, [PromoteAllScalars=true]),
    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"ID", Int64.Type}, {"LIMIT_BAL", Int64.Type}, {"SEX", Int64.Type}, {"EDUCATION", Int64.Type}, {"MARRIAGE", Int64.Type}, {"AGE", Int64.Type}, {"PAY_0", Int64.Type}, {"PAY_2", Int64.Type}, {"PAY_3", Int64.Type}, {"PAY_4", Int64.Type}, {"PAY_5", Int64.Type}, {"PAY_6", Int64.Type}, {"BILL_AMT1", Int64.Type}, {"BILL_AMT2", Int64.Type}, {"BILL_AMT3", Int64.Type}, {"BILL_AMT4", Int64.Type}, {"BILL_AMT5", Int64.Type}, {"BILL_AMT6", Int64.Type}, {"PAY_AMT1", Int64.Type}, {"PAY_AMT2", Int64.Type}, {"PAY_AMT3", Int64.Type}, {"PAY_AMT4", Int64.Type}, {"PAY_AMT5", Int64.Type}, {"PAY_AMT6", Int64.Type}, {"default.payment.next.month", Int64.Type}}),
    #"Removed Columns" = Table.RemoveColumns(#"Changed Type",{"PAY_0", "PAY_2", "PAY_3", "PAY_4", "PAY_5", "PAY_6", "BILL_AMT1", "BILL_AMT2", "BILL_AMT3", "BILL_AMT4", "BILL_AMT5", "BILL_AMT6", "PAY_AMT1", "PAY_AMT2", "PAY_AMT3", "PAY_AMT4", "PAY_AMT5", "PAY_AMT6"}),
    #"Added Custom" = Table.AddColumn(#"Removed Columns", "Custom", each {"Sep","Aug","July","jun","May","Apr"}),
    #"Expanded Custom" = Table.ExpandListColumn(#"Added Custom", "Custom"),
    #"Renamed Columns" = Table.RenameColumns(#"Expanded Custom",{{"Custom", "Months"}}),
    #"Changed Type1" = Table.TransformColumnTypes(#"Renamed Columns",{{"Months", type text}}),
    #"Reordered Columns" = Table.ReorderColumns(#"Changed Type1",{"ID", "Months", "LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE", "default.payment.next.month"}),
    #"Merged Queries" = Table.NestedJoin(#"Reordered Columns", {"ID", "Months"}, #"Transformed data for Repayment Analysis", {"ID", "Months"}, "Transformed data for Repayment Analysis", JoinKind.LeftOuter),
    #"Expanded Transformed data for Repayment Analysis" = Table.ExpandTableColumn(#"Merged Queries", "Transformed data for Repayment Analysis", {"Repayment Status/Bill delayed for that month(in months)"}, {"Repayment Status/Bill delayed for that month(in months)"}),
    #"Merged Queries1" = Table.NestedJoin(#"Expanded Transformed data for Repayment Analysis", {"ID", "Months"}, #"Transformed Data for Amount to pay Analysis", {"ID", "Months"}, "Transformed Data for Amount to pay Analysis", JoinKind.LeftOuter),
    #"Expanded Transformed Data for Amount to pay Analysis" = Table.ExpandTableColumn(#"Merged Queries1", "Transformed Data for Amount to pay Analysis", {"Bill Amount to Pay on the Month"}, {"Bill Amount to Pay on the Month"}),
    #"Merged Queries2" = Table.NestedJoin(#"Expanded Transformed Data for Amount to pay Analysis", {"ID", "Months"}, #"Transformed data for Bill payed Analysis", {"ID", "Months"}, "Transformed data for Bill payed Analysis", JoinKind.LeftOuter),
    #"Expanded Transformed data for Bill payed Analysis" = Table.ExpandTableColumn(#"Merged Queries2", "Transformed data for Bill payed Analysis", {"Bill payed"}, {"Bill payed"}),
    #"Reordered Columns1" = Table.ReorderColumns(#"Expanded Transformed data for Bill payed Analysis",{"ID", "Months", "LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE", "Repayment Status/Bill delayed for that month(in months)", "Bill Amount to Pay on the Month", "Bill payed", "default.payment.next.month"}),
    #"Renamed Columns1" = Table.RenameColumns(#"Reordered Columns1",{{"default.payment.next.month", "Default Flag"}}),
    #"Reordered Columns2" = Table.ReorderColumns(#"Renamed Columns1",{"ID", "LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE", "Months", "Repayment Status/Bill delayed for that month(in months)", "Bill Amount to Pay on the Month", "Bill payed", "Default Flag"}),
    #"Added Custom1" = Table.AddColumn(#"Reordered Columns2", "Late Payment charges", each if [#"Repayment Status/Bill delayed for that month(in months)"]>0 then [#"Repayment Status/Bill delayed for that month(in months)"]*40 else 0),
    #"Added Custom2" = Table.AddColumn(#"Added Custom1", "Loss From Default ($)", each ([Default Flag]*[LIMIT_BAL])*0.70),
    #"Added Custom3" = Table.AddColumn(#"Added Custom2", "interest  Income ", each [LIMIT_BAL]*(0.18/12)),
    Custom1 = Table.TransformColumns( #"Added Custom3",{{"SEX", each if _=1 then "Male" else "Female"},{"EDUCATION", each if _=1 then "Graduate" else if _= 2 then "University" else if _=3  then "High school"  else if _=4 then "Others" else "Unknown"},{"MARRIAGE", each if _=1 then "Married" else if _=2 then "Single" else "others"}}),
    #"Changed Type2" = Table.TransformColumnTypes(Custom1,{{"SEX", type text}, {"EDUCATION", type text}, {"MARRIAGE", type text}, {"Late Payment charges", Currency.Type}, {"Loss From Default ($)", Currency.Type}, {"interest  Income ", Currency.Type}}),
    #"Added Custom4" = Table.AddColumn(#"Changed Type2", "Total Revenue", each [Late Payment charges]+[#"interest  Income "]),
    #"Changed Type3" = Table.TransformColumnTypes(#"Added Custom4",{{"Total Revenue", Currency.Type}, {"Bill Amount to Pay on the Month", Currency.Type}, {"Bill payed", Currency.Type}}),
    #"Renamed Columns2" = Table.RenameColumns(#"Changed Type3",{{"Bill Amount to Pay on the Month", "Bill Amount to Pay"}}),
    #"Changed Type4" = Table.TransformColumnTypes(#"Renamed Columns2",{{"LIMIT_BAL", Currency.Type}}),
    #"Reordered Columns3" = Table.ReorderColumns(#"Changed Type4",{"ID", "LIMIT_BAL", "SEX", "EDUCATION", "MARRIAGE", "AGE", "Months", "Repayment Status/Bill delayed for that month(in months)", "Bill Amount to Pay", "Bill payed", "Late Payment charges", "Loss From Default ($)", "interest  Income ", "Total Revenue", "Default Flag"}),
    #"Added Custom5" = Table.AddColumn(#"Reordered Columns3", "Utilization %", each [Bill Amount to Pay]/[LIMIT_BAL]),
    #"Changed Type5" = Table.TransformColumnTypes(#"Added Custom5",{{"Utilization %", Percentage.Type}}),
    #"Added Custom6" = Table.AddColumn(#"Changed Type5", "Custom", each if [AGE]>=20 and [AGE]<=30 then "20-30" else if [AGE]>30 and [AGE]<=40 then "31-40" else if [AGE]>40 and [AGE]<=50 then "41-50" else if [AGE]>51 and [AGE]<=60 then "51-60" else if [AGE]>60 and [AGE]<=70 then "61-70" else "70+"),
    #"Changed Type6" = Table.TransformColumnTypes(#"Added Custom6",{{"Custom", type text}}),
    #"Added Custom7" = Table.AddColumn(#"Changed Type6", "  Limit Bucket", each if [LIMIT_BAL]<=200000 then "Low"  else if [LIMIT_BAL]>200000 and [LIMIT_BAL]<=500000 then "Medium" else "High"),
    #"Changed Type7" = Table.TransformColumnTypes(#"Added Custom7",{{"  Limit Bucket", type text}}),
    #"Renamed Columns3" = Table.RenameColumns(#"Changed Type7",{{"Custom", "Age_Bucket"}}),
    #"Added Custom8" = Table.AddColumn(#"Renamed Columns3", "Delayed or not(1=yes,0=N0)", each if [#"Repayment Status/Bill delayed for that month(in months)"]>0 then 1 else 0),
    #"Changed Type8" = Table.TransformColumnTypes(#"Added Custom8",{{"Delayed or not(1=yes,0=N0)",Int64.Type}})
in
    #"Changed Type8"